version: "3.9"

services:
  backend:
    build: ./backend
    container_name: courtierpro_backend
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: courtier
      DB_PASS: courtier
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: courtierpro_frontend
    ports:
      - "8081:80"

  db:
    image: postgres:15
    container_name: courtierpro_db
    environment:
      POSTGRES_DB: courtierpro
      POSTGRES_USER: courtier
      POSTGRES_PASSWORD: courtier
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
